program: main_ppo_count.py
name: mountaincar-ppo-count-sweep
method: grid
metric:
  goal: maximize
  name: episodic_return
parameters:
  gym-id:
    value: "MountainCar-v0"

  wandb-project-name:
    value: "ppo-tmp"

  track:
    value: True

  num-steps:
    value: 200

  total-timesteps:
    value: 500000

  count:
    values: [True]

  update-counts-step:
    values: [True]

  aggregate-function: 
    value : 'mean'

  anneal-lr:
    value: False

  seed: 
    values: [1, 2, 3, 4]

  

  
    