program: main_ppo_count.py
name: mountaincar-ppo-count-sweep
method: grid
metric:
  goal: maximize
  name: episodic_return
parameters:
  gym-id:
    value: "MountainCar-v0"

  wandb-project-name:
    value: "ppo-tmp"

  track:
    value: True

  num-steps:
    value: 200

  total-timesteps:
    value: 500000

  count:
    values: [True, False]

  update-counts-step:
    values: [True, False]

  aggregate-function: 
    value : 'mean'

  anneal-lr:
    value: False

  seed: 
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10 , 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

  

  
    